import Trending from "../models/Trending.js";
import { slugify } from "../utils/slugify.js";

export async function generateViralTopic() {
  const viralTopics = [
    "AI Breaking News",
    "Latest Shopping Trend",
    "Hot Travel Deal",
    "New Tech Release",
    "Viral TikTok Product"
  ];

  const title = viralTopics[Math.floor(Math.random() * viralTopics.length)];
  const slug = slugify(title);

  await Trending.create({
    title,
    slug,
    source: "AI-autogenerated"
  });

  return { status: "viral_created", slug };
}
